### ISSUE TITLE
Allow for testing with JCB

### ISSUE THREAD

**Issue by danholdaway** [NOAA-EMC/jcb-gdas#9]
1. In jcb-algorithms add the optional testing section in 3dvar / localensembleda YAML files.

```yaml
# Optionally test the application
{% if 3dvar_test_file is defined %}
test:
{% filter indent(width=2) %}
{% set 3dvar_test_file = 3dvar_test_file|default('3dvar_test', true) ~ '.yaml.j2' %}
{% include 3dvar_test_file %}
{% endfilter %}
{% endif %}
```

2. In jcb-gdas/model/atmosphere add 3dvar_test.yaml.j2

``` yaml
reference filename: {{reference_filename}}
test output filename: {{test_output_filename}}
integer tolerance: {{integer_tolerance}}
float relative tolerance: {{float_relative_tolerance}}
```

3. In GDASapp/test/atm/global-workflow modify the jcb-3dvar.yaml

3dvar_test_file: 3dvar_test
reference_filename: ./3dvar.ref
test_output_filename: ./3dvar.out
